In [1]:
import tensorflow as tf
import numpy as np

2025-04-05 18:31:45.088149: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-04-05 18:32:07.926624: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Input((5,)),
    tf.keras.layers.Dense(3, activation = 'relu'),
    tf.keras.layers.Dense(3, activation = 'relu'),
    tf.keras.layers.Dense(1)
])
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 3)              │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 3)              │            12 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 34 (136.00 B)

 Trainable params: 34 (136.00 B)

 Non-trainable params: 0 (0.00 B)

In [5]:
model.get_weights()

[array([[-0.5856736 , -0.34722853, -0.07142764],
        [-0.83059484,  0.84327275,  0.69788927],
        [-0.36352283,  0.4653539 , -0.68444496],
        [ 0.854593  ,  0.10911006, -0.7500073 ],
        [ 0.6249593 , -0.03334123,  0.83828694]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[-0.7844622 ,  0.92668843,  0.01148081],
        [ 0.9856701 ,  0.17767239,  0.55978155],
        [ 0.8170264 ,  0.88097   ,  0.8334906 ]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[ 0.5403869],
        [-0.9536976],
        [ 0.6031604]], dtype=float32),
 array([0.], dtype=float32)]

In [9]:
for l in model.get_weights():
    print(l.shape)

(5, 3)
(3,)
(3, 3)
(3,)
(3, 1)
(1,)


In [6]:
input = np.random.randn(5)
print(input)

[-0.06639924  1.82608733 -0.48022676 -0.83469193 -0.86759439]


In [8]:
model.predict(np.array([input]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 267ms/step


array([[1.051967]], dtype=float32)